### ISSUE TITLE
OSError -6

### ISSUE THREAD

**Issue by springjools** [fizista/micropython-umqtt.simple2#18]
Trying to install like in the wiki, but replacing upip with mip. But I get the OSerror -6:

> >>> import mip
> >>> mip.install("micropython-umqtt.simple2")
> Installing micropython-umqtt.simple2 (latest) from https://micropython.org/pi/v2 to /lib
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "mip/__init__.py", line 1, in install
>   File "mip/__init__.py", line 1, in _install_package
>   File "mip/__init__.py", line 1, in _install_json
>   File "urequests.py", line 180, in get
>   File "urequests.py", line 76, in request
> OSError: -6

I suppose this has something to do with the upip/mip migration. I used to be able to install like this.

**Describe the bug**

**To Reproduce**
For example a piece of code that can be pasted into a micropython console.

**Details (please complete the following information):**
 - Device board: rpi pico W
 - Micropython version: 1.20
 - Library version [e.g. 0.1]

**Comment by springjools** [comment]
Any updates?
